import{S as g,a as S,i as d}from"./assets/vendor-56025df1.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const v="/goit-js-hw-12/assets/bi_x-octagon-ddf7add7.svg",u=document.querySelector(".search-input"),b=document.querySelector(".search-form"),l=document.querySelector(".gallery");let i=1,q="";const c={key:"41300766-2a2685b0426849001fa971f21",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40},L={overlayOpacity:.8,captionsData:"alt",captionDelay:250};let m="https://pixabay.com/api/?";const w=new g(".gallery a",L),f=async(s,o)=>{await S.get(s).then(({data:r})=>{if(!r.hits[0]){d.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",messageColor:"#FAFAFB",position:"topRight",iconUrl:v,iconColor:"#ffffff",maxWidth:432,messageSize:16}),document.querySelector(".load-more-btn")&&document.querySelector(".load-more-btn").remove(),l.innerHTML="";return}const a=Math.ceil(r.totalHits/c.per_page);if(i===a){d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",maxWidth:432,messageSize:16}),document.querySelector(".load-more-btn")&&document.querySelector(".load-more-btn").remove(),document.querySelector(".loader")&&document.querySelector(".loader").remove();return}M(r),window.scrollBy({top:o,behavior:"smooth"})}).catch(r=>{document.querySelector(".loader")&&document.querySelector(".loader").remove(),console.log(r)})};b.addEventListener("submit",s=>{s.preventDefault(),q!==u.value&&(l.innerHTML="",c.q=u.value),document.querySelector(".loader")&&document.querySelector(".loader").remove(),document.querySelector(".load-more-btn")&&document.querySelector(".load-more-btn").remove(),l.insertAdjacentHTML("afterend",'<span class="loader"></span>'),i=1;const o=m+new URLSearchParams(c)+`&page=${i}`;u.value="",f(o,0)});const M=s=>{let o=s.hits.map(({webformatURL:a,largeImageURL:e,tags:t,likes:n,views:p,comments:h,downloads:y})=>`<li class="gallery-item">
        <a class="gallery-link" href=${e}>
          <img class="gallery-image" src=${a} data-source=${e} alt="${t}" width="360" height="200"/>
          <ul class="image-stats">
            <li class="stats-item"><h3 class="stat-title">Likes</h3><p class="stat-value">${n}</p></li>
            <li class="stats-item"><h3 class="stat-title">Views</h3><p class="stat-value">${p}</p></li>
            <li class="stats-item"><h3 class="stat-title">Comments</h3><p class="stat-value">${h}</p></li>
            <li class="stats-item"><h3 class="stat-title">Downloads</h3><p class="stat-value">${y}</p></li>
          </ul>  
          </a>
        </li>`).join(""),r='<button type="submit" class="load-more-btn">Load more</button>';document.querySelector(".loader").remove(),l.insertAdjacentHTML("beforeend",o),l.insertAdjacentHTML("afterend",r),document.querySelector(".load-more-btn").addEventListener("click",a=>{a.preventDefault(),document.querySelector(".load-more-btn").remove(),l.insertAdjacentHTML("afterend",'<span class="loader"></span>'),i+=1;const e=m+new URLSearchParams(c)+`&page=${i}`,t=document.querySelector(".gallery-item").getBoundingClientRect().height*2;f(e,t)}),w.refresh()};
//# sourceMappingURL=commonHelpers.js.map
